### ISSUE TITLE
Errors on running with yarn dev

### ISSUE THREAD

**Issue by NoozAbooz** [ottomated/turtle-gambit#19]
Hello!
First of all, I saw https://github.com/ottomated/turtle-gambit/issues/3 and https://github.com/ottomated/turtle-gambit/issues/7. I did apply the fixes mentioned in them are they were quite helpful.

Problem is, I get this issue when running it now
```
yarn run v1.22.10Downloads\turtle-gambit>yarn dev
warning ..\..\package.json: No license field
$ tsc && node lib/index.js
ERROR: The process with PID 18328 (child process of PID 9764) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 12828 (child process of PID 9764) could not be terminated.
Reason: There is no running instance of the task.
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: net::ERR_CONNECTION_REFUSED at http://localhost:3000/
    at navigate (C:\Users\mobilegmYT\Downloads\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:101:37)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async FrameManager.navigateFrame (C:\Users\mobilegmYT\Downloads\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:75:17)
    at async Frame.goto (C:\Users\mobilegmYT\Downloads\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:385:12)
    at async Page.goto (C:\Users\mobilegmYT\Downloads\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\Page.js:662:12)
    at async Window.load (C:\Users\mobilegmYT\Downloads\turtle-gambit\node_modules\carlo\lib\carlo.js:347:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Michael\Downloads\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\helper.js:108:27)
    at Page.goto (C:\Users\mobilegmYT\Downloads\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\Page.js:662:49)
    at Page.<anonymous> (C:\Users\mobilegmYT\Downloads\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\helper.js:109:23)
    at Window.load (C:\Users\mobilegmYT\Downloads\turtle-gambit\node_modules\carlo\lib\carlo.js:347:22)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It doesn't seem to be like any of the other errors people have gotten.

**Comment by Myoozik** [comment]
Run the following commands as shown below

1. run `yarn dev` in Turtle-Gambit\frontend\
2. run `yarn dev` in Turtle-Gambit\

**Comment by NoozAbooz** [comment]
![image](https://user-images.githubusercontent.com/44128563/107295314-56111f00-6a2c-11eb-9f4b-24bb7693ba76.png)

**Comment by NoozAbooz** [comment]
Wait nvm, I forgot to install react.

**Comment by NoozAbooz** [comment]
Ayy I got it working! Thanks for the help!
![image](https://user-images.githubusercontent.com/44128563/107299871-99bc5680-6a35-11eb-8b26-fcc311d9636b.png)
