### ISSUE TITLE
not starting the window on my pc

### ISSUE THREAD

**Issue by zaze06** [ottomated/turtle-gambit#28]
Hi i try to run the gambit but i get this when I try to run `yarn dev`
```
(node:33224) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_REFUSED at http://localhost:3000/
    at navigate (C:\Users\zacharias\Desktop\gambit\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:101:37)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FrameManager.navigateFrame (C:\Users\zacharias\Desktop\gambit\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:75:17)
    at async Frame.goto (C:\Users\zacharias\Desktop\gambit\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:385:12)
    at async Page.goto (C:\Users\zacharias\Desktop\gambit\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\Page.js:662:12)
    at async Window.load (C:\Users\zacharias\Desktop\gambit\turtle-gambit\node_modules\carlo\lib\carlo.js:347:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\zacharias\Desktop\gambit\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\helper.js:108:27)
    at Page.goto (C:\Users\zacharias\Desktop\gambit\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\Page.js:662:49)
    at Page.<anonymous> (C:\Users\zacharias\Desktop\gambit\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\helper.js:109:23)
    at Window.load (C:\Users\zacharias\Desktop\gambit\turtle-gambit\node_modules\carlo\lib\carlo.js:347:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zaze06** [comment]
think i have found out way
