### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by FOREVEREALIZE** [ottomated/turtle-gambit#42]
@GameWorld had this issue:

as soon as I did yarn dev in the back end It opened up for a second then closed and I got this Error: net::ERR_CONNECTION_REFUSED at http://localhost:3000/
at navigate (C:\Users\Ehren_je8q7zl\OneDrive\Desktop\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:101:37)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async FrameManager.navigateFrame (C:\Users\Ehren_je8q7zl\OneDrive\Desktop\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:75:17)
at async Frame.goto (C:\Users\Ehren_je8q7zl\OneDrive\Desktop\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:385:12)
at async Page.goto (C:\Users\Ehren_je8q7zl\OneDrive\Desktop\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\Page.js:662:12)
at async Window.load (C:\Users\Ehren_je8q7zl\OneDrive\Desktop\turtle-gambit\node_modules\carlo\lib\carlo.js:347:5)
-- ASYNC --
at Frame. (C:\Users\Ehren_je8q7zl\OneDrive\Desktop\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\helper.js:108:27)
at Page.goto (C:\Users\Ehren_je8q7zl\OneDrive\Desktop\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\Page.js:662:49)
at Page. (C:\Users\Ehren_je8q7zl\OneDrive\Desktop\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\helper.js:109:23)
at Window.load (C:\Users\Ehren_je8q7zl\OneDrive\Desktop\turtle-gambit\node_modules\carlo\lib\carlo.js:347:22)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by FOREVEREALIZE** [comment]
First run the frontend and after that has loaded run the backend

**Comment by LostGameDev** [comment]
I have I ran the frontend then the backend and that's what I got I think there maybe something wrong with my yarn install

**Comment by LostGameDev** [comment]
all fixed I just had to reinstall node.js
