### ISSUE TITLE
Cannot read properties of undefined (reading 'createCDPSession')

### ISSUE THREAD

**Issue by PrintedScript** [ottomated/turtle-gambit#58]
Whenever I try to run yarn dev I get this error message I have no idea what to do since carlo.js is no longer maintained
```
C:\Users\User\Documents\turtle-gambit-master>yarn dev
yarn run v1.22.19
$ tsc && node lib/index.js
C:\Users\User\Documents\turtle-gambit-master\node_modules\carlo\lib\carlo.js:56
      this.browser_.target().createCDPSession().then(session => {
                            ^

TypeError: Cannot read properties of undefined (reading 'createCDPSession')
    at App.init_ (C:\Users\User\Documents\turtle-gambit-master\node_modules\carlo\lib\carlo.js:56:29)
    at Object.launch (C:\Users\User\Documents\turtle-gambit-master\node_modules\carlo\lib\carlo.js:625:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Edit: Also I am running Windows 11 Pro

**Comment by PrintedScript** [comment]
Update: I have decided to fork the repo and rewrite most of the code so Carlo is no longer needed https://github.com/PrintedScript/turtle-control

**Comment by FOREVEREALIZE** [comment]
This is sick. I am definitely interested
