### ISSUE TITLE
cant run yarn dev command please help after running shows error below

### ISSUE THREAD

**Issue by BookaaGaming** [ottomated/turtle-gambit#61]
C:\Users\Owner\Desktop\turtle-gambit>yarn dev
yarn run v1.22.19
warning ..\..\package.json: No license field
$ tsc && node lib/index.js
C:\Users\Owner\Desktop\turtle-gambit\node_modules\carlo\lib\carlo.js:56
      this.browser_.target().createCDPSession().then(session => {
                            ^

TypeError: Cannot read property 'createCDPSession' of undefined
    at App.init_ (C:\Users\Owner\Desktop\turtle-gambit\node_modules\carlo\lib\carlo.js:56:29)
    at launch (C:\Users\Owner\Desktop\turtle-gambit\node_modules\carlo\lib\carlo.js:625:15)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Owner\Desktop\turtle-gambit>

**Comment by BookaaGaming** [comment]
on my http://localhost:5757/ i get only a message that says Upgrade Required

**Comment by Jackaroo05** [comment]
Same issue here, only I only have the Upgrade required message.
