### ISSUE TITLE
Error with trying to launch the the code

### ISSUE THREAD

**Issue by ItayKisous** [ottomated/turtle-gambit#9]
after doing `yarn dev`
I get the following error:

> yarn run v1.22.10
> $ tsc && node lib/index.js
> (node:17348) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_REFUSED at http://localhost:3000/
>     at navigate (C:\Users\Itay\Desktop\Programing\turtle-gambit-master\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:101:37)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async FrameManager.navigateFrame (C:\Users\Itay\Desktop\Programing\turtle-gambit-master\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:75:17)
>     at async Frame.goto (C:\Users\Itay\Desktop\Programing\turtle-gambit-master\node_modules\carlo\node_modules\puppeteer-core\lib\FrameManager.js:385:12)
>     at async Page.goto (C:\Users\Itay\Desktop\Programing\turtle-gambit-master\node_modules\carlo\node_modules\puppeteer-core\lib\Page.js:662:12)
>     at async Window.load (C:\Users\Itay\Desktop\Programing\turtle-gambit-master\node_modules\carlo\lib\carlo.js:347:5)
>   -- ASYNC --
>     at Frame.<anonymous> (C:\Users\Itay\Desktop\Programing\turtle-gambit-master\node_modules\carlo\node_modules\puppeteer-core\lib\helper.js:108:27)
>     at Page.goto (C:\Users\Itay\Desktop\Programing\turtle-gambit-master\node_modules\carlo\node_modules\puppeteer-core\lib\Page.js:662:49)
>     at Page.<anonymous> (C:\Users\Itay\Desktop\Programing\turtle-gambit-master\node_modules\carlo\node_modules\puppeteer-core\lib\helper.js:109:23)
>     at Window.load (C:\Users\Itay\Desktop\Programing\turtle-gambit-master\node_modules\carlo\lib\carlo.js:347:22)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:17348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:17348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Myoozik** [comment]
You also need to run `yarn dev` in ./turtle-gambit-master/frontend before running `yarn dev` in ./turtle-gambit-master/

**Comment by ItayKisous** [comment]
> 
> 
> You also need to run `yarn dev` in ./turtle-gambit-master/frontend before running `yarn dev` in ./turtle-gambit-master/

Sorry for asking a lot, but I'm just using yarn and npm for almost the first time :) 

So I did the 'yarn dev' in the frontend and it's all good.
Now when I run 'yarn dev' on the main folder I get:

> yarn run v1.22.10
> $ tsc && node lib/index.js
> src/index.ts:1:24 - error TS7016: Could not find a declaration file for module 'ws'. 'C:/Users/Itay/Desktop/Programing/ComputerCraft Lua/turtle-gambit/node_modules/ws/index.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`
> 
> 1 import { Server } from 'ws';
>                          ~~~~
> 
> src/index.ts:3:29 - error TS2307: Cannot find module 'carlo' or its corresponding type declarations.
> 
> 3 import { App, launch } from 'carlo';
>                               ~~~~~~~
> 
> src/index.ts:4:25 - error TS2307: Cannot find module 'path' or its corresponding type declarations.
> 
> 4 import { resolve } from 'path';
>                           ~~~~~~
> 
> src/index.ts:7:19 - error TS2307: Cannot find module 'p-queue' or its corresponding type declarations.
> 
> 7 import Queue from 'p-queue';
>                     ~~~~~~~~~
> 
> src/index.ts:23:23 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
> 
> 23  app.on('exit', () => process.exit());
>                          ~~~~~~~
> 
> src/index.ts:24:26 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
> 
> 24  app.serveFolder(resolve(process.cwd(), "frontend/out"));
>                             ~~~~~~~
> 
> src/index.ts:40:8 - error TS2339: Property 'on' does not exist on type 'World'.
> 
> 40  world.on('update', async (world) => {
>           ~~
> 
> src/index.ts:40:28 - error TS7006: Parameter 'world' implicitly has an 'any' type.
> 
> 40  world.on('update', async (world) => {
>                               ~~~~~
> 
> src/index.ts:46:48 - error TS7006: Parameter 'ws' implicitly has an 'any' type.
> 
> 46 wss.on('connection', async function connection(ws) {
>                                                   ~~
> 
> src/index.ts:49:10 - error TS2339: Property 'on' does not exist on type 'Turtle'.
> 
> 49      turtle.on('init', async () => {
>                ~~
> 
> src/index.ts:51:11 - error TS2339: Property 'on' does not exist on type 'Turtle'.
> 
> 51              turtle.on('update', () => app.evaluate(`if (window.setTurtles) window.setTurtles(${serializeTurtles()})`));
>                        ~~
> 
> src/index.ts:63:31 - error TS2550: Property 'values' does not exist on type 'ObjectConstructor'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2017' or later.
> 
> 63  return JSON.stringify(Object.values(turtles));
>                                  ~~~~~~
> 
> src/turtle.ts:1:23 - error TS7016: Could not find a declaration file for module 'ws'. 'C:/Users/Itay/Desktop/Programing/ComputerCraft Lua/turtle-gambit/node_modules/ws/index.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`
> 
> 1 import WebSocket from "ws";
>                         ~~~~
> 
> src/turtle.ts:2:30 - error TS2307: Cannot find module 'events' or its corresponding type declarations.
> 
> 2 import { EventEmitter } from 'events';
>                                ~~~~~~~~
> 
> src/turtle.ts:4:29 - error TS2307: Cannot find module 'crypto' or its corresponding type declarations.
> 
> 4 import { randomBytes } from 'crypto';
>                               ~~~~~~~~
> 
> src/turtle.ts:64:9 - error TS2339: Property 'emit' does not exist on type 'Turtle'.
> 
> 64              this.emit('init');
>                      ~~~~
> 
> src/turtle.ts:171:8 - error TS2339: Property 'emit' does not exist on type 'Turtle'.
> 
> 171     this.emit('update');
>              ~~~~
> 
> src/turtle.ts:175:8 - error TS2339: Property 'emit' does not exist on type 'Turtle'.
> 
> 175     this.emit('update');
>              ~~~~
> 
> src/turtle.ts:214:8 - error TS2339: Property 'emit' does not exist on type 'Turtle'.
> 
> 214     this.emit('update');
>              ~~~~
> 
> src/turtle.ts:266:9 - error TS2339: Property 'emit' does not exist on type 'Turtle'.
> 
> 266             this.emit('update');
>                      ~~~~
> 
> src/turtle.ts:395:12 - error TS2339: Property 'emit' does not exist on type 'Turtle'.
> 
> 395                                     this.emit('update');
>                                              ~~~~
> 
> src/world.ts:1:24 - error TS2307: Cannot find module 'node-json-db' or its corresponding type declarations.
> 
> 1 import { JsonDB } from 'node-json-db';
>                          ~~~~~~~~~~~~~~
> 
> src/world.ts:3:30 - error TS2307: Cannot find module 'events' or its corresponding type declarations.
> 
> 3 import { EventEmitter } from 'events';
>                                ~~~~~~~~
> 
> src/world.ts:12:8 - error TS2339: Property 'emit' does not exist on type 'World'.
> 
> 12      this.emit('update', this.getAllBlocks());
>              ~~~~
> 
> src/world.ts:31:10 - error TS2339: Property 'emit' does not exist on type 'World'.
> 
> 31                      this.emit('update', this.getAllBlocks());
>                              ~~~~
> 
> src/world.ts:36:8 - error TS2339: Property 'emit' does not exist on type 'World'.
> 
> 36      this.emit('update', this.getAllBlocks());
>              ~~~~
> 
> 
> Found 26 errors.
> 
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> C:\Users\Itay\Desktop\Programing\ComputerCraft Lua\turtle-gambit>npm i --save-dev @types/ws
> npm notice save @types/ws is being moved from dependencies to devDependencies
> npm WARN turtle-gambit@1.0.0 No repository field.
> 
> + @types/ws@7.4.0
> added 2 packages from 51 contributors and audited 20 packages in 1.129s
> found 0 vulnerabilities
> 
> 
> C:\Users\Itay\Desktop\Programing\ComputerCraft Lua\turtle-gambit>yarn dev
> yarn run v1.22.10
> $ tsc && node lib/index.js
> src/index.ts:3:29 - error TS2307: Cannot find module 'carlo' or its corresponding type declarations.
> 
> 3 import { App, launch } from 'carlo';
>                               ~~~~~~~
> 
> src/index.ts:7:19 - error TS2307: Cannot find module 'p-queue' or its corresponding type declarations.
> 
> 7 import Queue from 'p-queue';
>                     ~~~~~~~~~
> 
> src/world.ts:1:24 - error TS2307: Cannot find module 'node-json-db' or its corresponding type declarations.
> 
> 1 import { JsonDB } from 'node-json-db';
>                          ~~~~~~~~~~~~~~
> 
> 
> Found 3 errors.
> 
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ItayKisous** [comment]
> 
> 
> You also need to run `yarn dev` in ./turtle-gambit-master/frontend before running `yarn dev` in ./turtle-gambit-master/

Sorry for bugging you, but I'm just a newbie at all of this :) 

Now that's what I get

> yarn run v1.22.10
> $ tsc && node lib/index.js
> (node:13956) UnhandledPromiseRejectionWarning: Error: Protocol error (Browser.grantPermissions): Unknown permission type: clipboardRead
>     at C:\Users\Itay\Desktop\Programing\ComputerCraft Lua\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\Connection.js:74:56
>     at new Promise (<anonymous>)
>     at Connection.send (C:\Users\Itay\Desktop\Programing\ComputerCraft Lua\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\Connection.js:73:12)
>     at BrowserContext.overridePermissions (C:\Users\Itay\Desktop\Programing\ComputerCraft Lua\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\Browser.js:349:28)
>     at BrowserContext.<anonymous> (C:\Users\Itay\Desktop\Programing\ComputerCraft Lua\turtle-gambit\node_modules\carlo\node_modules\puppeteer-core\lib\helper.js:109:23)
>     at App.init_ (C:\Users\Itay\Desktop\Programing\ComputerCraft Lua\turtle-gambit\node_modules\carlo\lib\carlo.js:62:11)
>     at Object.launch (C:\Users\Itay\Desktop\Programing\ComputerCraft Lua\turtle-gambit\node_modules\carlo\lib\carlo.js:627:15)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:13956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:13956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by FaePhoenix** [comment]
Got the same Error, but ngrok also got an Error the moment i ran `yarn dev` in `./turtle-gambit/`
![Bild_2021-03-18_021411](https://user-images.githubusercontent.com/50998130/111558725-a0a25b80-878f-11eb-9f3f-9aec04b2cff6.png)
Would appreciate any help

**Comment by FaePhoenix** [comment]
After restarting everything I got the same two error-messages in ngrok and from yarn, but I get a empty pop-up window with a weird title now
![Bild_2021-03-18_021650](https://user-images.githubusercontent.com/50998130/111558958-00006b80-8790-11eb-9728-946b6b3a98b3.png)

**Comment by FaePhoenix** [comment]
After reinstalling the whole project (including the repo) it just worked... Dont know why
